[EXP-1076] Add subscriptions icons
pagarme/emblematic-icons pull request #59
Opened 2021-11-30 19:53 UTC by pedrogustavo

Adiciona ícones para botões da tela de subscriptions

2021-11-30 20:00 UTC, LorenaKauane submitted a review, later dismissed

2021-11-30 20:02 UTC, gabriel949 reviewed
Geralmente adiciona um arquivo 24px e um 32px, mas não tenho certeza se é uma regra

2021-11-30 20:04 UTC, rsmelo commented
esse ponto do @gabriel949 de adicionar os dois tamanhos

2021-11-30 21:41 UTC, pedrogustavo commented
Adicionei os ícones de 32px

2021-12-01 11:33 UTC, rsmelo requested changes

2021-12-01 11:33 UTC, rsmelo commented on svg/checkoutCard24.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M1.8 2H16.2C16.4122 2 16.6157 2.08194 16.7657 2.22781C16.9157 2.37367 17 2.5715 17 2.77778V7H5.8C5.58783 7 5.38434 7.08194 5.23431 7.22781C5.08429 7.3
acho que aqui ficou com conflito

2021-12-02 14:14 UTC, rsmelo submitted a review, later dismissed

2021-12-02 18:05 UTC, gabriel949 reviewed
Tava vendo o preview dos svgs aqui e tá ficando tudo preto, tá certo?

2021-12-03 16:47 UTC, Hrfreire commented on svg/checkoutCard24.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
acho que o padrão dos arquivos é com a primeira letra maiúscula, acho que tem que corrigir em todos os arquivos desse PR

2021-12-03 16:47 UTC, Hrfreire commented on svg/checkoutCard24.svg
> +<path d="M0 0H24V24H0V0Z" fill="currentColor"/>
acho que essa linha aqui pode ser removida.. é como se ela tivesse vindo com fundo branco, e ai tá agora que tá com "currentColor" tá ficando tudo da mesma cor... nesse svg a gente não quer com fundo

2021-12-03 16:47 UTC, Hrfreire commented on svg/checkoutCard32.svg
> +<path d="M0 0H32V32H0V0Z" fill="currentColor"/>
remover essa linha aqui

2021-12-03 16:47 UTC, Hrfreire commented on svg/share24.svg
> +<path d="M0 0H24V24H0V0Z" fill="currentColor"/>
remover essa linha aqui

2021-12-03 16:47 UTC, Hrfreire commented on svg/share32.svg
> +<path d="M0 0H32V32H0V0Z" fill="currentColor"/>
remover essa linha aqui

2021-12-03 18:10 UTC, Hrfreire reviewed
Faltou mudar o nome dos arquivos pra seguir o padrão, mudar
checkoutCard24.svg  para CheckoutCard24.svg por exemplo.

E ai acho que dá gente tentar consolidar esses commits, pra deixar a árvore mais limpa. Resetar os commits e tentar commitar novamente já com as coisas certas. Se precisar de ajuda, pinga alguém do time..

2021-12-06 23:58 UTC, Hrfreire approved these changes

2021-12-07 12:45 UTC, gabriel949 approved these changes

2021-12-07 12:58 UTC, merged